Update apt-linux-modules-extra.yml

diff --git a/.github/workflows/apt-linux-modules-extra.yml b/.github/workflows/apt-linux-modules-extra.yml
--- a/.github/workflows/apt-linux-modules-extra.yml
+++ b/.github/workflows/apt-linux-modules-extra.yml
@@ -14,7 +14,7 @@ permissions:
 
 jobs:
   test:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v3
       - uses: docker/setup-qemu-action@v2
@@ -28,23 +28,23 @@ jobs:
       - name: Load additional kernel modules needed for OPI like VRF
         run: sudo modprobe -v vrf
 
-      - name: Start containers
-        run: docker-compose up --build --force-recreate --detach opi-test
+      # - name: Start containers
+      #   run: docker-compose up --build --force-recreate --detach opi-test
 
-      - name: Run Tests
-        run: |
-          set -x
-          name=$(docker-compose ps | grep opi-test | awk '{print $1}')
-          rc=$(docker wait "${name}")
-          if [ "${rc}" != "0" ]; then
-              echo "opi-test failed:"
-              docker logs "${name}"
-              exit 1
-          fi
-      - name: Logs
-        if: always()
-        run: docker-compose logs
+      # - name: Run Tests
+      #   run: |
+      #     set -x
+      #     name=$(docker-compose ps | grep opi-test | awk '{print $1}')
+      #     rc=$(docker wait "${name}")
+      #     if [ "${rc}" != "0" ]; then
+      #         echo "opi-test failed:"
+      #         docker logs "${name}"
+      #         exit 1
+      #     fi
+      # - name: Logs
+      #   if: always()
+      #   run: docker-compose logs
 
-      - name: Stop containers
-        if: always()
-        run: docker-compose down --volumes --remove-orphans
+      # - name: Stop containers
+      #   if: always()
+      #   run: docker-compose down --volumes --remove-orphans
